# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af13c49e12087864a142190067b5e405d772aa7ebf5a0156d69538053a6c5015009f7096c6d642e3737d625745841766e0a3d8eb4b0ccc875509e7948bd71995

test:
  secret_key_base: 4a0a4ac8a7b616d44b14dee52beb01e399855063a1fcce9d1931d471f13b9c2a890825e202d641714ccbc95a7bd94ae072d52c4a3d9ec35d9426e7d76477ae24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
